apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: rreddy821/simple-reverse-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
         limits:
             memory: "1024Mi"
             cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
